name: Extension Test On PR Dispatch
on:
  push:
    branches:
      - test-workflow
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  build-ui-and-server:
    uses: meshery/meshery/.github/workflows/build-ui-server-reusable-workflow.yml@master
    secrets:
      NODE_VERSION: ${{ secrets.NODE_VERSION }}
      GO_VERSION: ${{ secrets.GO_VERSION }}
  tests-ui-e2e:
    needs: [build-ui-and-server]
    name: UI end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Meshery code
        uses: actions/checkout@v4
        with:
          repository: meshery/meshery
          fetch-depth: 1
          path: meshery
      - name: Check out meshery-consul code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: layer5io/meshery-consul
          path: ./meshery-consul
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: meshery
          path: meshery/server/cmd/
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ secrets.GO_VERSION }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: "kind-cluster"
      - name: Create a out/ folder in meshery ui
        run: |
          mkdir -p meshery/ui/out
          mkdir -p meshery/provider-ui/out/

      - name: Download Meshery-ui artifacts
        uses: actions/download-artifact@v4
        with:
          name: meshery-ui-build
          path: meshery/ui/out/

      - name: Download Meshery-provider-ui artifacts
        uses: actions/download-artifact@v4
        with:
          name: meshery-provider-ui build
          path: meshery/provider-ui/out/

      - name: Update /etc/hosts
        run: echo "127.0.0.1 mesherylocal.layer5.io" | sudo tee -a /etc/hosts
      - name: Run meshery-consul
        run: |
          mkdir -p /home/runner/.meshery/bin
          cd ./meshery-consul
          go run main.go &
          sleep 60
      - name: Run backend
        working-directory: meshery
        env:
          PROVIDER_BASE_URLS: https://meshery.layer5.io
          PORT: 9081
          ADAPTER_URLS: "mesherylocal.layer5.io:10000 mesherylocal.layer5.io:10001 mesherylocal.layer5.io:10002 mesherylocal.layer5.io:10003 mesherylocal.layer5.io:10004 mesherylocal.layer5.io:10008 mesherylocal.layer5.io:10009 mesherylocal.layer5.io:10007"
        run: |
          cd server/cmd
          chmod +x ./main
          ./main &
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: make test-setup-ui

      - name: Run  Tests
        id: run_tests
        working-directory: meshery
        run: |
          echo 'test-results<<EOF' >> $GITHUB_OUTPUT
          make test-ui >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        env:
          PROVIDER_TOKEN: ${{ secrets.PROVIDER_TOKEN }}
          MESHERY_SERVER_URL: "http://localhost:9081"
          REMOTE_PROVIDER_URL: "https://meshery.layer5.io"
          REMOTE_PROVIDER_USER_EMAIL: ${{ secrets.LAYER5_CLOUD_TESTING_BOT_EMAIL }}
          REMOTE_PROVIDER_USER_PASSWORD: ${{ secrets.LAYER5_CLOUD_TESTING_BOT_PASSWORD }}

