name: Meshery End-to-End Tests with mesheryui
on:
  workflow_dispatch:
    inputs:
      branch_name:
        required: true
        type: string
      pr_number:
        required: false
        type: string
    secrets:
      PROVIDER_TOKEN:
        required: true
      NODE_VERSION:
        required: true
      GO_VERSION:
        required: true
      GH_ACCESS_TOKEN:
        required: true
      LAYER5_CLOUD_USERNAME:
        required: true
      LAYER5_CLOUD_PASSWORD:
        required: true
      LAYER5_CLOUD_TESTING_BOT_EMAIL:
        required: true
      LAYER5_CLOUD_TESTING_BOT_PASSWORD:
        required: true

jobs:
  comment-starting-point:
    runs-on: ubuntu-latest
    steps:
      - name: comment starting point
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "DevRish/meshery"
          number: ${{ inputs.pr_number }}
          id: ui-test
          message: "Starting [Meshery Extensions tests](https://github.com/layer5labs/meshery-extensions-packages/actions/runs/${{ github.run_id }})..."
          recreate: true
  build-ui-and-server:
    uses: meshery/meshery/.github/workflows/build-ui-server-reusable-workflow.yml@master
    secrets:
      NODE_VERSION: ${{ secrets.NODE_VERSION }}
      GO_VERSION: ${{ secrets.GO_VERSION }}
  comment-success:
    runs-on: ubuntu-latest
    needs: [build-ui-and-server]
    steps:
      - name: comment progress
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "DevRish/meshery"
          number: ${{ inputs.pr_number }}
          id: ui-test
          message: ":heavy_check_mark: Meshery UI and Meshery Server builds complete."
          append: true
  tests-ui-e2e:
    needs: [build-ui-and-server]
    name: UI end-to-end tests
    runs-on: ubuntu-latest
    outputs:
      test-results: ${{ steps.run_tests.outputs.test-results }}
    steps:
      - name: comment progress start
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "DevRish/meshery"
          number: ${{ inputs.pr_number }}
          id: ui-test
          message: ":heavy_check_mark: Setting up test environment..."
          append: true
      - name: Check out Meshery code
        uses: actions/checkout@v4
        with:
          repository: meshery/meshery
          fetch-depth: 1
          path: meshery
      - name: Check out meshery-istio code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: meshery/meshery-istio
          path: ./meshery-istio
      - name: Check out meshery-consul code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: meshery/meshery-consul
          path: ./meshery-consul
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: meshery
          path: meshery/server/cmd/
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ secrets.GO_VERSION }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: "kind-cluster"
      - name: Create a out/ folder in meshery ui
        run: |
          mkdir -p meshery/ui/out
          mkdir -p meshery/provider-ui/out/
      - name: Download Meshery-ui artifacts
        uses: actions/download-artifact@v4
        with:
          name: meshery-ui-build
          path: meshery/ui/out/
      - name: Download Meshery-provider-ui artifacts
        uses: actions/download-artifact@v4
        with:
          name: meshery-provider-ui build
          path: meshery/provider-ui/out/
      - name: Update /etc/hosts
        run: echo "127.0.0.1 mesherylocal.layer5.io" | sudo tee -a /etc/hosts
      - name: Run meshery-istio
        run: |
          mkdir -p /home/runner/.meshery/bin
          cd ./meshery-istio
          go run main.go &
          sleep 60
      - name: Run meshery-consul
        run: |
          mkdir -p /home/runner/.meshery/bin
          cd ./meshery-consul
          go run main.go &
          sleep 60
      - name: Run backend
        working-directory: meshery
        env:
          PROVIDER_BASE_URLS: https://meshery.layer5.io
          PORT: 9081
          ADAPTER_URLS: "mesherylocal.layer5.io:10000 mesherylocal.layer5.io:10001 mesherylocal.layer5.io:10002 mesherylocal.layer5.io:10003 mesherylocal.layer5.io:10004 mesherylocal.layer5.io:10008 mesherylocal.layer5.io:10009 mesherylocal.layer5.io:10007"
        run: |
          cd server/cmd
          chmod +x ./main
          ./main &
          sleep 60
      - name: Install dependencies
        working-directory: meshery
        run: make test-setup-ui
      - name: comment progress start
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "DevRish/meshery"
          number: ${{ inputs.pr_number }}
          id: ui-test
          message: ":heavy_check_mark: Test environment ready. Starting tests..."
          append: true
      - name: Run Tests
        id: run_tests
        working-directory: meshery
        run: |
          echo 'test-results<<EOF' >> $GITHUB_OUTPUT
          make test-ui >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
        env:
          PROVIDER_TOKEN: ${{ secrets.PROVIDER_TOKEN }}
          MESHERY_SERVER_URL: "http://localhost:9081"
          REMOTE_PROVIDER_URL: "https://meshery.layer5.io"
          REMOTE_PROVIDER_USER_EMAIL: ${{ secrets.LAYER5_CLOUD_TESTING_BOT_EMAIL }}
          REMOTE_PROVIDER_USER_PASSWORD: ${{ secrets.LAYER5_CLOUD_TESTING_BOT_PASSWORD }}
      - name: comment the summary
        uses: hasura/comment-progress@v2.3.0
        if: always()
        with:
          message: |
            ${{join(steps.run_tests.outputs.*, '\n')}}
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "DevRish/meshery"
          number: ${{ inputs.pr_number }}
          id: ui-test
          append: true

      # - uses: actions/upload-artifact@v4
      #   if: ${{ !cancelled() }}
      #   with:
      #     name: playwright-report
      #     path: meshery-extensions/meshmap/test-results/
      #     retention-days: 30

      - name: Comment Test failure
        uses: hasura/comment-progress@v2.3.0
        if: ${{ failure()  }}
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "DevRish/meshery"
          number: ${{ inputs.pr_number }}
          id: ui-test
          message: ":x: One or more tests have failed."
          append: true

      - name: Comment Final Status
        if: always()
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "DevRish/meshery"
          number: ${{ inputs.pr_number }}
          id: ui-test
          message: ":heavy_check_mark: Extension [test results](https://github.com/layer5labs/meshery-extensions-packages/actions/runs/${{ github.run_id }})."
          append: true